### ISSUE TITLE
Interrupts Conflict Resolution

### ISSUE THREAD

**Issue by oldmanegan** [PaulStoffregen/SoftwareSerial#1]
Hi Paul,
I encountered an issue with SoftwareSerial and PCINT. After researching I found modifying the SoftwareSerial.cpp file to avoid the port group that I was using for PCINT ought to work. I found your version on GitHub and used it for my purposes. I just commented out the def for PCINT1 and it has worked so far. 
/*#if defined(PCINT1_vect)
ISR(PCINT1_vect)
{
  SoftwareSerial::handle_interrupt();
}
#endif
*/
Now, is it possible to move these port group defs to a "User_Setup.h" file so that SoftwareSerial will read that first to determine which ports to monitor for serial activity, giving guys like me an easier path to changing and avoiding the PCINT conflict? I would love it if these defs could be in the Arduino .ino file for ease of set up and access, is this possible?
Thanks,

John

**Comment by PaulStoffregen** [comment]
Sorry, Arduino doesn't work that way.  Your sketch code can't cause a change within SoftwareSerial.cpp.  You need to edit the SoftwareSerial.cpp file, as you've done.

This is an issue specific to AVR chips.  On ARM, interrupt vectors can be reassigned at runtime.  Since I'm not longer developing new features on AVR chips, I'm going to close this issue.
